[package]
name = "trust_hardcore"
version = "0.1.0"
authors = ["negamartin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
